name: Node.js CI

on: [push, pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run unit tests
        run: npm run test:unit

      - name: Run e2e tests
        run: |
          npm run test:e2e

      - name: Lint code
        run: npm run lint

      - name: Build project
        run: npm run build
      
      - name: Upload web server artifacts
        uses: actions/upload-artifact@v4
        with:
          name: web-server-build
          path: dist/
          retention-days: 7
